version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy #EC2의 경로로서 빌드파일을 Ec2의 경로로 전달
    overwrite: true
# permissions:
#   - object: /
#     pattern: "**"
#     owner: ec2-user
#     group: ec2-user
# hooks:
#   AfterInstall:
#     - location: stop.sh
#       timeout: 60
#   ApplicationStart:
#     - location: start.sh
#       timeout: 60
